version: '3.1'

services:

  db:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=coin
      - POSTGRES_PASSWORD=coindbpass
      - POSTGRES_DB=coin
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"