spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: coin
    password: coindbpass
# Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
# Server configuration
server:
  port: 8100 #set your port
  
redis:
  url: "redis://localhost:6379"
  password: "eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81"