# Spring Boot configuration
spring:
  profiles:
    active: dev
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true

# Server configuration
server:
  port: 4001 #set your port